import { Karla } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/components/modal/dynamic-modal";
import { ThemeProviderWrapper } from "@/theme/context-them";
import { AuthProvider } from "./context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const karla = Karla({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${karla.className} ${inter.className}`}>
        <ThemeProviderWrapper>
          <ModalProvider>
            <AuthProvider>{children}</AuthProvider>
          </ModalProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}